### ISSUE TITLE
Same size makes them collide and fight for a position

### ISSUE THREAD

**Issue by caycun** [caycun/tdash#1]
Config yaml file to replicate:
```yaml
- command: "ping google.com"
  size: 20
  direction: 1
- command: "ping facebook.com"
  size: 40
  direction: 2
- command: "ping youtube.com"
  size: 40
  direction: 2
- command: "lsblk"
  size: 10
  direction: 1
  ```

As you can see, both ping commands have the same size which is `40`. They are clashing/colliding because they have the same size.

![](https://media.discordapp.net/attachments/1213318162456641620/1269119210181886054/Issue.gif?ex=66aee6de&is=66ad955e&hm=cc5bf45e961b45a1538f8e09ccc3a886839de37f282244e963a4e169e094478c&=)
